USE [Pepro]
GO

CREATE OR ALTER PROCEDURE usp_XoaMaDien
    @MaDien NVARCHAR(50)
AS BEGIN
    SET NOCOUNT ON;

    EXEC sp_MSForeachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';
    DELETE FROM DIEN WHERE MAD = @MaDien;
    EXEC sp_MSForeachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL';
END;
GO

CREATE OR ALTER PROCEDURE usp_XoaMaNuoc
    @MaNuoc NVARCHAR(50)
AS BEGIN
    SET NOCOUNT ON;

    EXEC sp_MSForeachTable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL';
    DELETE FROM NUOC WHERE MAN = @MaNuoc;
    EXEC sp_MSForeachTable 'ALTER TABLE ? CHECK CONSTRAINT ALL';
END;
GO

CREATE OR ALTER PROCEDURE CalculateSalary
    @MaNhanVien NVARCHAR(10)
AS BEGIN
    SELECT
        ((LUONG.LUONGCOBAN * BACLUONG.HESOBL) + 
        (LUONG.LUONGCOBAN * CHUCVU.HESOPHUCAP * 0.1) - 
        (ISNULL(TIENNHA.TONGTIEN, 0) + 
        (BOPHANCHAMCONG.SONGAYNGHIBHXH * LUONG.LUONGCOBAN * 0.1) + 
        (BOPHANCHAMCONG.SONGAYNGHIKHONGLYDO * LUONG.LUONGCOBAN * 0.3))) AS TongLuong
    FROM LUONG
        INNER JOIN NGACHLUONG
                ON LUONG.MANL = NGACHLUONG.MANL
        INNER JOIN BACLUONG
                ON LUONG.MABL = BACLUONG.MABL
        INNER JOIN CHUCVU
                ON LUONG.MACV = CHUCVU.MACV
        INNER JOIN BOPHANCHAMCONG
                ON LUONG.MACC = BOPHANCHAMCONG.MACC
        INNER JOIN TIENNHA
                ON LUONG.MATN = TIENNHA.MANTT
    WHERE LUONG.MANV = @MaNhanVien;
END
GO